FROM rust:1-trixie AS vscode

WORKDIR /workspace

RUN <<EOF
apt-get update
apt-get install -y vim git curl git-secrets unzip less bash-completion npm procps
echo "source /usr/share/bash-completion/completions/git" >> ~/.bashrc
rustup component add rustfmt rust-analyzer rust-docs

# Install GitHub CLI
(type -p wget >/dev/null || (apt update && apt install wget -y)) \
	&& mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& apt update \
	&& apt install gh -y

npm i -g @anthropic-ai/claude-code
EOF

